baseURL = 'https://example.org/'
#languageCode = 'zh-tw'
defaultContentLanguage = 'zh-tw'
title = 'Ferrari Liquor Website'
theme = 'ferrari_gallery'


[params]
  defaultTheme = "dark"
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  [params.author]
    email = "phunc20@gmail.com"
    name = "phunc20"
  [params.socialIcons]
    facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/"
    github = "https://github.com/phunc20/ferrari_website_hugo"
    youtube = "https://www.youtube.com/@phunc20"
    email = "mailto:phunc20@gmail.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"


[languages]
  [languages.zh-tw]
    disabled = false
    languageCode = 'zh-tw'
    languageName = 'ğŸ‡¹ğŸ‡¼ ä¸­æ–‡'
    languageDirection = 'ltr'
    title = 'æ³•æ‹‰åˆ©é…’åŠ'
    weight = 1
    [languages.zh-tw.params]
      subtitle = 'éš¨ä¾¿äº‚å¯«ä¸€é€š'

  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'ğŸ‡ºğŸ‡¸ English'
    title = 'Ferrari Liquor'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'

  [languages.fr]
    disabled = false
    languageCode = 'fr-US'
    languageDirection = 'ltr'
    languageName = 'ğŸ‡«ğŸ‡· FranÃ§ais'
    title = 'Site en FranÃ§ais'
    weight = 3
    [languages.fr.params]
      subtitle = 'Reference, Tutorials, and Explanations'

  [languages.ja]
    disabled = false
    languageCode = 'ja'
    languageDirection = 'ltr'
    languageName = 'ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª'
    title = 'to be specified'
    weight = 4
    [languages.ja.params]
      subtitle = 'Reference, Tutorials, and Explanations'

  [languages.vn]
    disabled = true
    languageCode = 'vn-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 5
    [languages.vn.params]
      subtitle = 'Reference, Tutorials, and Explanations'

  [languages.de]
    disabled = true
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Projekt Dokumentation'
    weight = 7
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und ErklÃ¤rungen'
